### ISSUE TITLE
Missing data data/lizard.mat

### ISSUE THREAD

**Issue by Bibi56** [jzy3d/jzy3d-api#175]
**Describe the bug**
In https://github.com/jzy3d/jzy3d-api/blob/453cefe05c4bfff58765e178ab99362ea205d5bc/jzy3d-tutorials/src/main/java/org/jzy3d/demos/volume/LizardVolumeDemo.java#L38
a file is referred but is missing, therefore an NPE demo ;-).

**Screenshots**
Exception in thread "main" java.lang.NullPointerException
	at org.jzy3d.chart.ChartLauncher.configureControllers(ChartLauncher.java:46)
	at org.jzy3d.chart.ChartLauncher.openChart(ChartLauncher.java:38)
	at org.jzy3d.chart.ChartLauncher.openChart(ChartLauncher.java:32)
	at org.jzy3d.chart.ChartLauncher.openChart(ChartLauncher.java:27)
	at org.jzy3d.analysis.AnalysisLauncher.open(AnalysisLauncher.java:23)
	at org.jzy3d.analysis.AnalysisLauncher.open(AnalysisLauncher.java:12)
	at org.jzy3d.demos.volume.LizardVolumeDemo.main(LizardVolumeDemo.java:27)

**Reproducibility**
Run `org.jzy3d.demos.volume.LizardVolumeDemo`

**Versions (please complete the following information):**
 - Jzy3D: jzy3d-api-2.0.0-SNAPSHOT-Windows10
 - JVM / JDK: irrelevant
 - GPU: irrelevant
 - OS: irrelevant

**Additional context**
Looking with a search engine for this file returns funny results ;-).

**Comment by jzy3d** [comment]
https://github.com/jzy3d/jzy3d-api/blob/master/jzy3d-tutorials/src/main/java/org/jzy3d/demos/volume/LizardVolumeDemo.java#L18 will help you!

**Comment by Bibi56** [comment]
A big thanks for the speedy answer. I was running the examples to see the possibilities before investigating more, so I missed the comment!
I suggest following modification:

<pre>
        String fileName = "data/lizard.mat";
        if (!new File(fileName).exists()) {
            System.err.println("You need to donwload http://download.jzy3d.org/objfiles/lizard.mat and save it as " + fileName);
            System.exit(1);
        }
         try {
            MatFileReader mfr = new MatFileReader(fileName);
</pre>

**Comment by jzy3d** [comment]
Thanks for the suggestion, I'll try to add it soon.
