### ISSUE TITLE
Let Github CI run tests on multiple OS versions

### ISSUE THREAD

**Issue by jzy3d** [jzy3d/jzy3d-api#205]
Physical machines 
- [x] MacOS 10.15.3
- [x] MacOS 11 + ARM processor (Silicon)
- [x] Ubuntu 20.04 (can build and test project, but JVM 9 & 10 are killed when ran from Github Actions)
- [x] Windows 10

Java
- [ ] 8 - dropped since one submodule requires Java 9 (jzy3d-tests-java9)
- [x] 9 - can't reliably run tests with Java 9 on Ubuntu 20 (but working manually)
- [x] 11
- [x] 14

JOGL
- [x] 2.4-rc4

Misc improvements
- [x] Fix the very slow mocked jGL tests (TestContinuousAndOnDemandRendering, TestDepthRange)
- [ ] Add test name on frame title bar for monitoring progress
- [ ] [Unstable tests on EmulGL](https://github.com/jzy3d/jzy3d-api/runs/3950108561?check_suite_focus=true#step:4:392)

**Comment by jzy3d** [comment]
Ubuntu

```
Error:  org.jzy3d.chart.factories.TestNativePainterFactory.hasGoodSettingsToMakeOnscreenRenderingWithColor  Time elapsed: 0.377 s  <<< ERROR!
com.jogamp.nativewindow.NativeWindowException: X11Util.Display: Unable to create a display(nil) connection. Thread pool-2-thread-2
	at org.jzy3d.chart.factories.TestNativePainterFactory.newAbstractNativePainterFactory(TestNativePainterFactory.java:51)
	at org.jzy3d.chart.factories.TestNativePainterFactory.hasGoodSettingsToMakeOnscreenRenderingWithColor(TestNativePainterFactory.java:37)
```

**Comment by jzy3d** [comment]
Windows 2019 [fails with missing OpenGL function](https://github.com/jzy3d/jzy3d-api/runs/3892399585?check_suite_focus=true)

```
com.jogamp.opengl.GLException: Method "glGenBuffers" not available
	at jogamp.opengl.gl4.GL4bcImpl.glGenBuffers(GL4bcImpl.java:10276)
	at org.jzy3d.plot3d.primitives.vbo.drawable.DrawableVBO2.registerVertices(DrawableVBO2.java:588)
	at org.jzy3d.plot3d.primitives.vbo.drawable.DrawableVBO2.setData(DrawableVBO2.java:539)
```

**Comment by jzy3d** [comment]
https://github.com/jzy3d/jzy3d-api/issues/1555

**Comment by jzy3d** [comment]
Compatibility tests using Jzy3D 2.0.1-SNAPSHOT + JOGL 2.4

![image](https://user-images.githubusercontent.com/2334960/142420892-7a1c2faf-65d7-4337-b840-153010914aba.png)
