### ISSUE TITLE
[Native] Newt Canvas Crash

### ISSUE THREAD

**Issue by jzy3d** [jzy3d/jzy3d-api#210]
JOGL 2.4
JDK Azul 11
Mac OS 11.4 (BigSur) on ARM64 CPU

Surefire test do not output any file. Running manually from the IDE simply crash the app. 

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  4.789 s
[INFO] Finished at: 2021-11-16T17:14:12+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M5:test (default-test) on project jzy3d-native-jogl-newt: There are test failures.
[ERROR] 
[ERROR] Please refer to /Users/martin/Dev/jzy3d/public/jzy3d-api/jzy3d-native-jogl-newt/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /Users/martin/Dev/jzy3d/public/jzy3d-api/jzy3d-native-jogl-newt && /Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/bin/java -Djogamp.common.utils.locks.Lock.timeout=20000 -jar /Users/martin/Dev/jzy3d/public/jzy3d-api/jzy3d-native-jogl-newt/target/surefire/surefirebooter3627394357515409096.jar /Users/martin/Dev/jzy3d/public/jzy3d-api/jzy3d-native-jogl-newt/target/surefire 2021-11-16T17-14-07_825-jvmRun1 surefire6809755853688366357tmp surefire_08103590534049019196tmp
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 133
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /Users/martin/Dev/jzy3d/public/jzy3d-api/jzy3d-native-jogl-newt && /Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/bin/java -Djogamp.common.utils.locks.Lock.timeout=20000 -jar /Users/martin/Dev/jzy3d/public/jzy3d-api/jzy3d-native-jogl-newt/target/surefire/surefirebooter3627394357515409096.jar /Users/martin/Dev/jzy3d/public/jzy3d-api/jzy3d-native-jogl-newt/target/surefire 2021-11-16T17-14-07_825-jvmRun1 surefire6809755853688366357tmp surefire_08103590534049019196tmp
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 133
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:748)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:305)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:265)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1314)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1159)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:932)
[ERROR] 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
[ERROR] 	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
[ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
[ERROR] 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
[ERROR] 	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:972)
[ERROR] 	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:293)
[ERROR] 	at org.apache.maven.cli.MavenCli.main(MavenCli.java:196)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)

**Comment by AlexisDrogoul** [comment]
Just to mention that Newt canvases, used in their SWT flavour, work well on BigSur, Monterey and Ubuntu 20 in Gama. Mouse and Keyboard processing do not seem to suffer any delays neither.
