### ISSUE TITLE
[Native] Unit test failure on Windows 10 + Java 17

### ISSUE THREAD

**Issue by jzy3d** [jzy3d/jzy3d-api#230]
These tests fail on Windows 10 + Azul Zulu JDK 17 (see errors below). Also discussed [here](https://github.com/jzy3d/jogl/issues/4).

These tests do pass with 
- Windows 10 + Java [8, 11]
- macOS 11.4 + Java 17
- Ubuntu 20 + Java 17

```
[ERROR] Tests run: 8, Failures: 0, Errors: 5, Skipped: 0, Time elapsed: 0.369 s <<< FAILURE! - in org.jzy3d.plot3d.rendering.view.TestViewModeAndCameraClippingPlanes
[ERROR] org.jzy3d.plot3d.rendering.view.TestViewModeAndCameraClippingPlanes.givenNativeOnscreenChart_whenAddSimpleSurface_AfterOpen_thenBoundsAreCorrect  Time elapsed: 0.115 s  <<< ERROR!
com.jogamp.opengl.GLException:
Unable to determine GraphicsConfiguration: WindowsWGLGraphicsConfiguration[DefaultGraphicsScreen[WindowsGraphicsDevice[type .windows, connection decon, unitID 0, handle 0x0, owner false, NullToolkitLock[obj 0x6b358342]], idx 0], pfdID 7, ARB-Choosen true,
        requested GLCaps[rgba 8/8/8/8, opaque, accum-rgba 0/0/0/0, dp/st/ms 16/0/0, dbl, mono  , hw, GLProfile[GL2/GL4bc.hw], on-scr[.]],
        chosen    GLCaps[wgl vid 7 arb: rgba 8/8/8/8, opaque, accum-rgba 16/16/16/16, dp/st/ms 16/0/0, dbl, mono  , hw, GLProfile[GL2/GL4bc.hw], on-scr[.]]]
        at org.jzy3d.plot3d.rendering.view.TestViewModeAndCameraClippingPlanes.openAndWaitForInitializationCompletion(TestViewModeAndCameraClippingPlanes.java:482)
        at org.jzy3d.plot3d.rendering.view.TestViewModeAndCameraClippingPlanes.givenNativeOnscreenChart_whenAddSimpleSurface_AfterOpen_thenBoundsAreCorrect(TestViewModeAndCameraClippingPlanes.java:267)

[ERROR] org.jzy3d.plot3d.rendering.view.TestViewModeAndCameraClippingPlanes.givenNativeOnscreenChart_whenEmpty_thenBoundsAreCorrect  Time elapsed: 0.004 s  <<< ERROR!
com.jogamp.opengl.GLException:
Unable to determine GraphicsConfiguration: WindowsWGLGraphicsConfiguration[DefaultGraphicsScreen[WindowsGraphicsDevice[type .windows, connection decon, unitID 0, handle 0x0, owner false, NullToolkitLock[obj 0x6b358342]], idx 0], pfdID 7, ARB-Choosen true,
        requested GLCaps[rgba 8/8/8/8, opaque, accum-rgba 0/0/0/0, dp/st/ms 16/0/0, dbl, mono  , hw, GLProfile[GL2/GL4bc.hw], on-scr[.]],
        chosen    GLCaps[wgl vid 7 arb: rgba 8/8/8/8, opaque, accum-rgba 16/16/16/16, dp/st/ms 16/0/0, dbl, mono  , hw, GLProfile[GL2/GL4bc.hw], on-scr[.]]]
        at org.jzy3d.plot3d.rendering.view.TestViewModeAndCameraClippingPlanes.openAndWaitForInitializationCompletion(TestViewModeAndCameraClippingPlanes.java:482)
        at org.jzy3d.plot3d.rendering.view.TestViewModeAndCameraClippingPlanes.givenNativeOnscreenChart_whenEmpty_thenBoundsAreCorrect(TestViewModeAndCameraClippingPlanes.java:114)

[ERROR] org.jzy3d.plot3d.rendering.view.TestViewModeAndCameraClippingPlanes.givenNativeOnscreenChart_whenAddSimpleSurface_BeforeOpen_thenBoundsAreCorrect  Time elapsed: 0.011 s  <<< ERROR!
com.jogamp.opengl.GLException:
Unable to determine GraphicsConfiguration: WindowsWGLGraphicsConfiguration[DefaultGraphicsScreen[WindowsGraphicsDevice[type .windows, connection decon, unitID 0, handle 0x0, owner false, NullToolkitLock[obj 0x6b358342]], idx 0], pfdID 7, ARB-Choosen true,
        requested GLCaps[rgba 8/8/8/8, opaque, accum-rgba 0/0/0/0, dp/st/ms 16/0/0, dbl, mono  , hw, GLProfile[GL2/GL4bc.hw], on-scr[.]],
        chosen    GLCaps[wgl vid 7 arb: rgba 8/8/8/8, opaque, accum-rgba 16/16/16/16, dp/st/ms 16/0/0, dbl, mono  , hw, GLProfile[GL2/GL4bc.hw], on-scr[.]]]
        at org.jzy3d.plot3d.rendering.view.TestViewModeAndCameraClippingPlanes.openAndWaitForInitializationCompletion(TestViewModeAndCameraClippingPlanes.java:482)
        at org.jzy3d.plot3d.rendering.view.TestViewModeAndCameraClippingPlanes.givenNativeOnscreenChart_whenAddSimpleSurface_BeforeOpen_thenBoundsAreCorrect(TestViewModeAndCameraClippingPlanes.java:226)

[ERROR] org.jzy3d.plot3d.rendering.view.TestViewModeAndCameraClippingPlanes.givenNativeOnscreenChart_whenAddVBOSurface_AfterOpen_thenBoundsAreCorrect  Time elapsed: 0.006 s  <<< ERROR!
com.jogamp.opengl.GLException:
Unable to determine GraphicsConfiguration: WindowsWGLGraphicsConfiguration[DefaultGraphicsScreen[WindowsGraphicsDevice[type .windows, connection decon, unitID 0, handle 0x0, owner false, NullToolkitLock[obj 0x6b358342]], idx 0], pfdID 7, ARB-Choosen true,
        requested GLCaps[rgba 8/8/8/8, opaque, accum-rgba 0/0/0/0, dp/st/ms 16/0/0, dbl, mono  , hw, GLProfile[GL2/GL4bc.hw], on-scr[.]],
        chosen    GLCaps[wgl vid 7 arb: rgba 8/8/8/8, opaque, accum-rgba 16/16/16/16, dp/st/ms 16/0/0, dbl, mono  , hw, GLProfile[GL2/GL4bc.hw], on-scr[.]]]
        at org.jzy3d.plot3d.rendering.view.TestViewModeAndCameraClippingPlanes.openAndWaitForInitializationCompletion(TestViewModeAndCameraClippingPlanes.java:482)
        at org.jzy3d.plot3d.rendering.view.TestViewModeAndCameraClippingPlanes.givenNativeOnscreenChart_whenAddVBOSurface_AfterOpen_thenBoundsAreCorrect(TestViewModeAndCameraClippingPlanes.java:418)

[ERROR] org.jzy3d.plot3d.rendering.view.TestViewModeAndCameraClippingPlanes.givenNativeOnscreenChart_whenAddVBOSurface_BeforeOpen_thenBoundsAreCorrect  Time elapsed: 0.009 s  <<< ERROR!
com.jogamp.opengl.GLException:
Unable to determine GraphicsConfiguration: WindowsWGLGraphicsConfiguration[DefaultGraphicsScreen[WindowsGraphicsDevice[type .windows, connection decon, unitID 0, handle 0x0, owner false, NullToolkitLock[obj 0x6b358342]], idx 0], pfdID 7, ARB-Choosen true,
        requested GLCaps[rgba 8/8/8/8, opaque, accum-rgba 0/0/0/0, dp/st/ms 16/0/0, dbl, mono  , hw, GLProfile[GL2/GL4bc.hw], on-scr[.]],
        chosen    GLCaps[wgl vid 7 arb: rgba 8/8/8/8, opaque, accum-rgba 16/16/16/16, dp/st/ms 16/0/0, dbl, mono  , hw, GLProfile[GL2/GL4bc.hw], on-scr[.]]]
        at org.jzy3d.plot3d.rendering.view.TestViewModeAndCameraClippingPlanes.openAndWaitForInitializationCompletion(TestViewModeAndCameraClippingPlanes.java:482)
        at org.jzy3d.plot3d.rendering.view.TestViewModeAndCameraClippingPlanes.givenNativeOnscreenChart_whenAddVBOSurface_BeforeOpen_thenBoundsAreCorrect(TestViewModeAndCameraClippingPlanes.java:381)

[INFO] Running org.jzy3d.plot3d.rendering.view.TestView_Interactive
true
[WARNING] Tests run: 2, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0.035 s - in org.jzy3d.plot3d.rendering.view.TestView_Interactive
[INFO]
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR]   TestViewModeAndCameraClippingPlanes.givenNativeOnscreenChart_whenAddSimpleSurface_AfterOpen_thenBoundsAreCorrect:267->openAndWaitForInitializationCompletion:482 » GL
[ERROR]   TestViewModeAndCameraClippingPlanes.givenNativeOnscreenChart_whenAddSimpleSurface_BeforeOpen_thenBoundsAreCorrect:226->openAndWaitForInitializationCompletion:482 » GL
[ERROR]   TestViewModeAndCameraClippingPlanes.givenNativeOnscreenChart_whenAddVBOSurface_AfterOpen_thenBoundsAreCorrect:418->openAndWaitForInitializationCompletion:482 » GL
[ERROR]   TestViewModeAndCameraClippingPlanes.givenNativeOnscreenChart_whenAddVBOSurface_BeforeOpen_thenBoundsAreCorrect:381->openAndWaitForInitializationCompletion:482 » GL
[ERROR]   TestViewModeAndCameraClippingPlanes.givenNativeOnscreenChart_whenEmpty_thenBoundsAreCorrect:114->openAndWaitForInitializationCompletion:482 » GL
[INFO]
[ERROR] Tests run: 30, Failures: 0, Errors: 5, Skipped: 1

```

**Comment by jzy3d** [comment]
As mentioned in the JOGL bugzilla ticket, running the JVM with 

```
--add-exports java.base/java.lang=ALL-UNNAMED
--add-exports java.desktop/sun.awt=ALL-UNNAMED
--add-exports java.desktop/sun.java2d=ALL-UNNAMED
``` 

fixes the problem
