### ISSUE TITLE
java.lang.InternalError when running SurfaceDemo

### ISSUE THREAD

**Issue by Plenglin** [jzy3d/jzy3d-api#94]
Running the `org.jzy3d.demos.surface.SurfaceDemo` in the tutorials gives me the following error:
```
Exception in thread "main" java.lang.InternalError: XXX0 profile[1]: GL3bc -> profileImpl GL4bc !!! not mapped 
	at com.jogamp.opengl.GLProfile.computeProfileMap(GLProfile.java:2071)
	at com.jogamp.opengl.GLProfile.initProfilesForDeviceCritical(GLProfile.java:1954)
	at com.jogamp.opengl.GLProfile.initProfilesForDevice(GLProfile.java:1875)
	at com.jogamp.opengl.GLProfile.initProfilesForDefaultDevices(GLProfile.java:1842)
	at com.jogamp.opengl.GLProfile.access$000(GLProfile.java:80)
	at com.jogamp.opengl.GLProfile$1.run(GLProfile.java:230)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.jogamp.opengl.GLProfile.initSingleton(GLProfile.java:216)
	at com.jogamp.opengl.GLProfile.isAvailable(GLProfile.java:300)
	at com.jogamp.opengl.GLProfile.isAvailable(GLProfile.java:315)
	at org.jzy3d.chart.Settings.detectProfile(Settings.java:30)
	at org.jzy3d.chart.Settings.<init>(Settings.java:14)
	at org.jzy3d.chart.Settings.getInstance(Settings.java:47)
	at org.jzy3d.analysis.AnalysisLauncher.open(AnalysisLauncher.java:17)
	at org.jzy3d.analysis.AnalysisLauncher.open(AnalysisLauncher.java:13)
	at org.jzy3d.demos.surface.SurfaceDemo.main(SurfaceDemo.java:18)
```

**Comment by jzy3d** [comment]
You may use [EmulGL](https://github.com/jzy3d/jzy3d-api/tree/master/jzy3d-emul-gl) instead of JOGL for rendering with Jzy3D. EmulGL is made to enhance charts portability across computers. 

See links to examples in the readme.

**Comment by jzy3d** [comment]
Hi,
After recently publishing 2.0 release version on maven repo, I started `2.0.1-SNAPSHOT` by bumping JOGL to a more recent version (2.4.0 RC produced in 2021). 
You may give a try based on the updated tutorials [here](https://github.com/jzy3d/jzy3d-api/tree/master/jzy3d-tutorials). Thanks in advance for your feedback!

**Comment by jzy3d** [comment]
Hi @astridyu , did the `2.0.1-SNAPSHOT` version fixed your error?

**Comment by astridyu** [comment]
> Hi @astridyu , did the `2.0.1-SNAPSHOT` version fixed your error?

Sorry, I have no idea. It was 4 years ago and I don't remember what I was doing back then.
